### ISSUE TITLE
CKEditor 4.22.1 which isn't supported anymore

### ISSUE THREAD

**Issue by epoch18** [ppfeufer/aa-bulletin-board#113]
### Bug Description

Not a bug. 
Warning message while migrating:

WARNINGS:
?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS . You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)
?: (templates.E003) 'filters' is used for multiple template tag modules: 'fittings.templatetags.filters', 'moonstuff.templatetags.filters'

### Steps to Reproduce
: manage.py migrate

- App Version: 2.0.0
- Alliance Auth Version: 4.0.1
- Browser and Version: n/a

**Comment by ppfeufer** [comment]
Please read the update information » https://github.com/ppfeufer/aa-bulletin-board/releases/tag/v2.0.0
